### ISSUE TITLE
train and test data

### ISSUE THREAD

**Issue by ice-m** [wsdream/WSRec#1]
excuse me for my very basic Qusetion. I am learning :) I downloaded java version and I tried to run it in eclipse. It needs to have train and test data. i guess i should randomly generate them and manually make  dataFolder's data :-1:  but it would be more interesting if the code itself generate those.
thanks.

**Comment by jimzhu** [comment]
Thanks for your interest and comments!
We have already implement this functionality in our Python code in Master branch. For the Java code, we only provide it for reference and would not update it anymore. Sorry for this. But you are welcome to take any modification and request for a push.

**Comment by ice-m** [comment]
Sorry for prejudgment comment. I don't know python very well. 
after installing "Dependencies" and trying to correct indentation errors, the compiler cant find core folder. "ImportError: No module named core". I add "sys.path.append('src\\core')" to "evaluator.py" hope to pass the error but unfortunately it didn't work either. Is there any easy way to regenerate your results?
thanks alot

**Comment by jimzhu** [comment]
Which method did you run? Make sure that you install Python 2.7 and numpy 1.8.1 or above

**Comment by ice-m** [comment]
I copied all files to python directory and tried to run "run_rt.py".
I Installed: 
   1-python-2.7
   2-numpy-1.8.1-win32-superpack-python2.7
   3-scipy-0.13.3-win32-superpack-python2.7

**Comment by jimzhu** [comment]
I see. You use Windows right? As claimed in the readme file, the current version is only tested on Linux. If you want to use Windows, you need to install Cython on your Windows machine, and re-compile each method.

**Comment by ice-m** [comment]
I cant Install Cython either :) but I try to compile it with Visual studio. thanks for your guidence.

**Comment by jimzhu** [comment]
Hi, we just update a page on how to run on Windows: https://github.com/WS-DREAM/WSRec/wiki/How-to-Run-on-Windows.

This may help you!

**Comment by ice-m** [comment]
Hi Dr Zhu,
It was so nice of you to help me out

**Comment by ice-m** [comment]
Hi Dr Zhu,
I was wondering if there is any implementation for your "greedy order
algorithm: CloudRank" ?
Regards

**Comment by jimzhu** [comment]
Yes. But it is still being tested. If you want a copy, please send an email to wsdream.maillist AT gmail.com

**Comment by ice-m** [comment]
Hi Dr Zhu,
I am a windows user and I have hard time compiling one of your projects
(Cloud rank). i don't understand the errors (i attached the building
process errors[image: Inline image 3][image: Inline image 1][image: Inline
image 2]). would you please guide me? thanks.
